const mongoose = require('mongoose')
const Review = require('../models/ReviewModel')
const nodemailer = require ('nodemailer');
const uniqid = require('uniqid');

exports.list = (req, res) => {
    Review.find({tutorEmail: req.body.tutorEmail, confirmed: true}, function(err, revs){
        if(err) res.status(200).send(err);
        else res.status(200).send(revs);
    })
}

exports.create = (req, res) =>{
    const newReview = new Review({
        studentId: uniqid(),
        studentName: req.body.name,
        studentEmail: req.body.studentEmail,
        review: req.body.review,
        rating: req.body.rating,
        tutorEmail: req.body.tutorEmail, 
        confirmed: false
    })
    console.log(newReview);
    // if(req.comments) {
    //     tutor.comments = req.comments;
    // }
    // tutor.rating = null;
    // tutor.review = null;
    newReview.save(function(err) {
        if(err) {
            res.statusCode = 400;
            res.end({'error' : 'Review could not be saved'});
        } else{
            let transport = nodemailer.createTransport({
                host: "smtp.mailtrap.io",
                port: 2525,
                auth: {
                  user: "f7a2eb04d78a86", //generated by Mailtrap
                  pass: "ed26fed5bc0a7c" //generated by Mailtrap
                }
            })

            let site = (process.env.NODE_ENV === 'production') ? "https://uf-tutor-match.herokuapp.com" : "localhost:3000"
            let link = site + '/reviews/' + 'create/'+newReview.studentId;
            let mailOptions = {
                from: '"UF Tutor Match" <donotreply@uftutormatch.com>',
                to: newReview.studentEmail,
                subject: 'Review',
                text: 'Thank you for reviewing a tutor post. Click on the link below to activate your review.\n' + link,
                html: '<p>Thank you for creating a new tutor post. Click on the link below to activate your post.</p><a href=' + link + '>Activate Review</a>'
            }
    
            transport.sendMail(mailOptions, (error, info) => {
                if (error) {
                    return console.log(error);
                }
                console.log('Message sent: %s', info.messageId);
            })
            
            res.send(newReview);

            
        }
    })
}

exports.postReview = (req, res) => {
    console.log(req.params.id);
    Review.updateOne({studentId: req.params.id}, {confirmed: true}, function(err, rev){
        if(err) res.status(200).send(err);
        
        else res.status(200).json({message: "Review has been activated"});
    })
}